[package]
name = "tinymd"
version = "0.1.0"
authors = ["Marco Serrato <marco.serrato@icloud.com>"]
edition = "2018"
description = "A tiny markdown compiler."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
